### ISSUE TITLE
APK Android Studio

### ISSUE THREAD

**Issue by PeterKW** [ReVancedTeam/revanced-integrations#4]
Is Android Studio required for compiling an APK to test ReVanced? 
Are there particular instructions for what's required to export to an APK?

**Comment by oSumAtrIX** [comment]
At this moment, you can't use the integrations with the stock apk. Only with the vanced apk, since all patches are already there.

**Comment by PeterKW** [comment]
> At this moment, you can't use the integrations with the stock apk. Only with the vanced apk, since all patches are already there. 

I have the vanced application? How do I export this version from GitHub to update it on my phone?

I tried using the the emulator to have a look at what the Android Studio code was doing but I wasn't sure that I was doing it right

**Comment by oSumAtrIX** [comment]
Please wait until we release proper documentations and guides, this is the wrong place to ask for help
